# Generated by Django 2.1.4 on 2019-01-14 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190114_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('91d050b3-8281-4271-86c7-3656bb8bcd95'), help_text='Unique id', primary_key=True, serialize=False),
        ),
    ]
