# Generated by Django 2.1.4 on 2019-01-15 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190114_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name'], 'permissions': (('can_author_edit', 'Can edit author'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('53306c45-9204-46ea-8ebc-eb04601a1b96'), help_text='Unique id', primary_key=True, serialize=False),
        ),
    ]
